GET {{content_host}}/content/course/1
Accept: application/json

###
###
GET http://localhost:8081/hello1

###
GET http://localhost:8082/hello2

###
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": "1",
  "publishStatus": "null"
}


###
GET {{gateway_host}}/content/hello
Content-Type: application/json






